/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ques_res;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javapro.Login;
import javax.swing.JOptionPane;


public class Math extends javax.swing.JFrame {
    String username;
    int count=0;
    String sub="Math";
    String grade=null;
    /**
     * Creates new form Math
     */
    public Math(String usr) {
        username=usr;
        initComponents();
         setSize(517,720);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.ButtonGroup();
        b2 = new javax.swing.ButtonGroup();
        b3 = new javax.swing.ButtonGroup();
        b4 = new javax.swing.ButtonGroup();
        b5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        q1a1 = new javax.swing.JRadioButton();
        q1a2 = new javax.swing.JRadioButton();
        q1a3 = new javax.swing.JRadioButton();
        q1a4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        q2a1 = new javax.swing.JRadioButton();
        q2a2 = new javax.swing.JRadioButton();
        q2a3 = new javax.swing.JRadioButton();
        q2a4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        q3a1 = new javax.swing.JRadioButton();
        q3a2 = new javax.swing.JRadioButton();
        q3a3 = new javax.swing.JRadioButton();
        q3a4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        q4a1 = new javax.swing.JRadioButton();
        q4a2 = new javax.swing.JRadioButton();
        q4a3 = new javax.swing.JRadioButton();
        q4a4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        q5a1 = new javax.swing.JRadioButton();
        q5a2 = new javax.swing.JRadioButton();
        q5a3 = new javax.swing.JRadioButton();
        q5a4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel1.setText("Mathamatics");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("1)The average of first 50 natural numbers is ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 456, -1));

        b1.add(q1a1);
        q1a1.setText(" 25.30");
        getContentPane().add(q1a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, -1, -1));

        b1.add(q1a2);
        q1a2.setText("25.5");
        getContentPane().add(q1a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 82, -1, -1));

        b1.add(q1a3);
        q1a3.setText("25.00");
        getContentPane().add(q1a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        b1.add(q1a4);
        q1a4.setText("12.25");
        getContentPane().add(q1a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 123, -1, -1));

        jLabel3.setText("2)The number of 3-digit numbers divisible by 6, is");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, 424, -1));

        b2.add(q2a1);
        q2a1.setText("149");
        q2a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a1ActionPerformed(evt);
            }
        });
        getContentPane().add(q2a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        b2.add(q2a2);
        q2a2.setText("166");
        getContentPane().add(q2a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 196, -1, -1));

        b2.add(q2a3);
        q2a3.setText("150");
        getContentPane().add(q2a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        b2.add(q2a4);
        q2a4.setText("151");
        getContentPane().add(q2a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 237, -1, -1));

        jLabel4.setText("3) What is 1004 divided by 2?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 278, 456, -1));

        b3.add(q3a1);
        q3a1.setText("52");
        getContentPane().add(q3a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        b3.add(q3a2);
        q3a2.setText("502");
        q3a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a2ActionPerformed(evt);
            }
        });
        getContentPane().add(q3a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 310, -1, -1));

        b3.add(q3a3);
        q3a3.setText("520");
        getContentPane().add(q3a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 351, -1, -1));

        b3.add(q3a4);
        q3a4.setText("5002");
        getContentPane().add(q3a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 351, -1, -1));

        jLabel5.setText("4) A clock strikes once at 1 o’clock, twice at 2 o’clock, thrice at 3 o’clock and so on.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 392, 447, -1));

        jLabel6.setText(" How many times will it strike in 24 hours?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 412, -1, -1));

        b4.add(q4a1);
        q4a1.setText("78");
        q4a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a1ActionPerformed(evt);
            }
        });
        getContentPane().add(q4a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 444, -1, -1));

        b4.add(q4a2);
        q4a2.setText("136");
        q4a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a2ActionPerformed(evt);
            }
        });
        getContentPane().add(q4a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 444, -1, -1));

        b4.add(q4a3);
        q4a3.setText("156");
        q4a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a3ActionPerformed(evt);
            }
        });
        getContentPane().add(q4a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 485, -1, -1));

        b4.add(q4a4);
        q4a4.setText("196");
        q4a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a4ActionPerformed(evt);
            }
        });
        getContentPane().add(q4a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 485, -1, -1));

        jLabel7.setText("5)106 × 106 – 94 × 94 = ?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 526, 476, -1));

        b5.add(q5a1);
        q5a1.setText("2004");
        getContentPane().add(q5a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 558, -1, -1));

        b5.add(q5a2);
        q5a2.setText("2400");
        getContentPane().add(q5a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 558, -1, -1));

        b5.add(q5a3);
        q5a3.setText("1904");
        q5a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5a3ActionPerformed(evt);
            }
        });
        getContentPane().add(q5a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 599, -1, -1));

        b5.add(q5a4);
        q5a4.setText("1906");
        getContentPane().add(q5a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 599, -1, -1));

        jButton1.setFont(new java.awt.Font("Broadway", 0, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 656, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q2a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2a1ActionPerformed

    private void q3a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3a2ActionPerformed

    private void q4a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4a1ActionPerformed

    private void q4a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4a2ActionPerformed

    private void q4a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4a3ActionPerformed

    private void q4a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4a4ActionPerformed

    private void q5a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5a3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if (q1a2.isSelected())
      {
          count=count+4;
      }
      else if (q1a1.isSelected())
      {
          count--;
      }
      else if (q1a3.isSelected())
      {
          count--;
      }
      else if (q1a4.isSelected())
      {
          count--;
      }
      
      if (q2a3.isSelected())
      {
          count=count+4;
      }
      else if (q2a1.isSelected())
      {
          count--;
      }
      else if (q2a2.isSelected())
      {
          count--;
      }
      else if (q2a4.isSelected())
      {
          count--;
      }
      if (q3a2.isSelected())
      {
          count=count+4;
      }
      else if (q3a1.isSelected())
      {
          count--;
      }
      else if (q3a3.isSelected())
      {
          count--;
      }
      else if (q3a4.isSelected())
      {
          count--;
      }
      if (q4a3.isSelected())
      {
          count=count+4;
      }
      else if (q4a1.isSelected())
      {
          count--;
      }
      else if (q4a2.isSelected())
      {
          count--;
      }
      else if (q4a4.isSelected())
      {
          count--;
      }
      if (q5a2.isSelected())
      {
          count=count+4;
      }
      else if (q5a1.isSelected())
      {
          count--;
      }
      else if (q5a3.isSelected())
      {
          count--;
      }
      else if (q5a4.isSelected())
      {
          count--;
      }
      if ( count >= 15)
      {
          grade="A";
      }

else if (count >= 10 && count <15)
{
    grade= "B";
}

else if (count >=5 && count <10)
{
    grade ="C";
}

else if (count >=0 && count <5)
{
    grade ="D";
}

else
{
    grade = "E";
}

      
      try{
            Class.forName("com.mysql.jdbc.Driver");

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/examination","root","");
            Statement st=con.createStatement();
                String query1;
                query1 = "insert into mark_info values('"+username+"','"+count+"','"+sub+"','"+grade+"')";
                st.executeUpdate(query1);
                Result r=new Result(username,count,grade,sub);
                r.setVisible(true);
                this.setVisible(false);
            

        }catch (HeadlessException | ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Math.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usr=null;
                new Math(usr).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup b1;
    private javax.swing.ButtonGroup b2;
    private javax.swing.ButtonGroup b3;
    private javax.swing.ButtonGroup b4;
    private javax.swing.ButtonGroup b5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton q1a1;
    private javax.swing.JRadioButton q1a2;
    private javax.swing.JRadioButton q1a3;
    private javax.swing.JRadioButton q1a4;
    private javax.swing.JRadioButton q2a1;
    private javax.swing.JRadioButton q2a2;
    private javax.swing.JRadioButton q2a3;
    private javax.swing.JRadioButton q2a4;
    private javax.swing.JRadioButton q3a1;
    private javax.swing.JRadioButton q3a2;
    private javax.swing.JRadioButton q3a3;
    private javax.swing.JRadioButton q3a4;
    private javax.swing.JRadioButton q4a1;
    private javax.swing.JRadioButton q4a2;
    private javax.swing.JRadioButton q4a3;
    private javax.swing.JRadioButton q4a4;
    private javax.swing.JRadioButton q5a1;
    private javax.swing.JRadioButton q5a2;
    private javax.swing.JRadioButton q5a3;
    private javax.swing.JRadioButton q5a4;
    // End of variables declaration//GEN-END:variables
}
